### ISSUE TITLE
Landscape Autocorrelation

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#1]
The make_landscape() function creates a spatially autocorrelated binary grid of habitat types using a variogram model with given model defining the shape (e.g. exponential, gaussian, etc.. anything supported by gstat) and distance at which cell values become uncorrelated (the range). Short ranges lead to high heterogeneity, long ranges give large homogenous patches. The proportion of each habitat type can also be specified.
1. What variogram model should we use for distance decay? (Default is exponential.)
2. What set of ranges should we simulate over? Or just pick two?
3. What size grid should we do most simulations on? Maybe 128 x 128 so we can use log-scale spatial grains (1x1, 2x2, 4x4, 8x8, 16x16, 32x32, ....)?

**Comment by ahhurlbert** [comment]
1. Exponential seems fine.
2. Default (1/3 of landscape dimension) seems fine.
3. 128 x 128 is ok, but if this is really slow, I think 64 x 64 would be fine.
