### ISSUE TITLE
Detection probability

### ISSUE THREAD

**Issue by ahhurlbert** [hurlbertlab/core-transient-simulation#11]
One of the fundamental problems distinguishing transient species from rare species is that detection is less than 100%, so persistent rare species appear to be transient.

So it seems we need a sampling/detection function that determines what the community sample snapshot is from the true community. 

Can't remember if we talked about doing this spatially (i.e., what's really "present" is the community of a 3 x 3 set of cells, while the "sample" is just the single cell in the middle), or non-spatially.

Non-spatially seems easier, given landscape variability.

**Comment by jescoyle** [comment]
I have added a function summarize_sim() that samples a simulation result using a detection probability (or vector or probabilities that can differ among species). Basically, the function assumes that the probability of observing any given individual is _p_ and then returns "observed" species abundances after stochastically determining which individuals were observed.

When simulation results are summarized, we can then compare statistics based on the actual abundances and statistics calculated from detected abundances.
