### ISSUE TITLE
Summary statistics

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#12]
We need to decide which summary statistics should be calculated for a simulation run at a given spatial and temporal resolution and detection probability.

Here's a start.. please modify/add:
_(statistics calculated across spatial units at a given spatial resolution)_
- Mean/variance of richness in different occupancy categories (core/transient/indeterminate) 
- Mean/variance of abundance in different occupancy categories (core/transient/indeterminate) 
- Mean/variance of richness of biological core vs transient species
- Mean/variance of abundance of biological core vs transient species
- Mean/variance of proportion of actual core species classified as transients
- Mean/variance of proportion of actual transient species classified as core

Questions:

Should statistics be calculated in raw richness/abundance or in % based on number of species in the simulation and community size?

Are we interested in the relationship between local abundance and occupancy (e.g. number of rare core species)? If so, how should we quantify it?

**Comment by jescoyle** [comment]
I wrote a script 'summarize_simulation.R' to automatically summarize multiple runs from the same simulation (e.g. runs on the same set of parameters).

Here's how runs are summarized (see summarize_sim() at line 1863 in simulation_functions.R):

1) User sets time window for determining occupancy status and which grid cells should be summarized.

2) User sets breakpoints for temporal occupancy categories (not limited to 2).

3) Optional settings:
- which timepoints to aggregate before calculating occupancy status or richness/abundance
- detection probabilties
- how richness/abundance should be reported for the time window (e.g. mean across all time points, vs. just the last time point, vs. report all timepoints)

4) For each cell in each timepoint in the specified time window:
- calculate richness and abundance of species that are core vs. transient based on positive birth rates in the cell's given habitat type ('biological')
- calculate richness and abundance of species in each temporal occupancy category (from specified occupancy breakpoints)
- count number of biologically core and transient species in lowest and highest occupancy classes. Results in four categories: core-core, core-transient, transient-core, transient-transient.
- Recalculate community statistics after stochastically sampling at each given detection probability.

5) For each cell and detection probability, summarize community statistics across timepoints (mean, last, or all, see point 3).

6) For each detection probability, calculate the mean and variance of community statistics across all specified cells. Optionally calculate specified quantiles.

I am currently summarizing simulations using the following settings:
- all cells, aggregated at 1x1, 2x2, 4x4, 8x8, 16x16 
- time window = last 25 steps of the simulation for classifying occupancy, use the last time step to count species and abundance
- detection probabilities: 0.1, 0.2, 0.3, ..., 1
- calculate mean, var, median, 95th quantiles across spatial units (e.g. at 16x16 there are 4 units for a 32x32    @##grid).

QUESTIONS
- Are there any other basic statistics we should derive from the simulation?
- Is there another way I should do the summaries?

**Comment by ahhurlbert** [comment]
What about storing info on landscape composition at each spatial scale. Simplest metric would simply be % cover of the dominant habitat type (so ranges from 50-100% in theory).

**Comment by ahhurlbert** [comment]
What about storing info on landscape composition at each spatial scale. Simplest metric would simply be % cover of the dominant habitat type (so ranges from 50-100% in theory).

**Comment by ahhurlbert** [comment]
Did I miss it or are there summary plots that illustrate the temporal occupancy distribution summarized over all runs of identical parameter combos?

**Comment by jescoyle** [comment]
Sure- I'll add a summary function for the landscape. It will calculate %cover and a metric of heterogeneity/aggregation.

I haven't made a plot of the occupancy distribution yet.

**Comment by jescoyle** [comment]
I added a function to summarize the landscape. For a given spatial grain it returns:
- The proportion of spatial units that are the dominant habitat type (where habitat types are assigned to spatial units based on the majority of their constituent cells).
- The variance in habitat values, calculated based on bernoulli distribution var = p*(1-p).
- A heterogeneity metric which is just a variance:mean ratio corrected for finite count data ([citation](http://dx.doi.org/10.1046/j.1440-1703.2000.00326.x)). For each spatial unit it counts the number of cells that are the dominant habitat type. It then compares the variance and mean of these frequencies. A value of zero indicates random distribution at that scale.

Are there any other summary stats we want from the simulations?

**Comment by ahhurlbert** [comment]
I can't think of any others. @ethanwhite can chime in if he has any.

Would be useful to add a good README to the Results section here to guide folks (us!) to where the different types of output are and what they mean.

**Comment by ethanwhite** [comment]
I can't think of anything else. +1 to a good README. :+1:
