### ISSUE TITLE
Time for simulation and number of runs

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#13]
Time to decide how long to run simulations.

I have 8 runs on a 32 x 32 grid for 1000 time steps. The parameters used for the run are found [here](https://github.com/hurlbertlab/core-transient-simulation/blob/master/Code/p_converge32.txt). The results are plotted through time [here](https://github.com/hurlbertlab/core-transient-simulation/blob/master/Results/converge32_d-9_ind_run_summary_through_time.pdf). Plots show richness and abundance of core and transient species evaluated in time intervals of 25 steps. Each run is represented by a line (mean across spatial units) and shaded polygon (95th quantiles across spatial units). There are 8 runs on each plot to show both the variation across runs.

To me it looks like simulations need to be run for at least 250 time steps. What do you think?

I am also running simulations with different dispersal parameters on a 32 x 32 grid as well as one on a 64 x 64 grid to make sure that amount of time needed to reach equilibrium is not drastically different.

Given the wide variation among runs, we should probably do a fair number of runs on each set of parameters evaluated. How many? 20? 50? 100? 

The 32 x 32 grid with community size=100 is running at about 100 timesteps in 90 minutes. The 64 x 64 grid is running at about 100 timesteps in 4 hours. I can do 4 runs in parallel without having to request too much memory.

**Comment by ahhurlbert** [comment]
200-250 time steps looks good to me.

I am thinking 32 x 32 will be sufficient, since at 16x transients already basically go down to 0 for detection probability >.5.

Surprising amount of variation if I'm looking at the non-through-time run_summary right. 100 reps?

**Comment by jescoyle** [comment]
I think the variability across runs is coming from a combination of low number of species (40) and skewed SAD (birth rates drawn from a  lognormal distribution with P(x <= 8) = 0.999). Some runs end up with one two species with high birth rates while others don't. I think lots of runs is probably a good idea.

**Comment by ethanwhite** [comment]
Yeah, I'd been wondering about the low number of species showing up in the communities. Is that something we should be trying to increase?

**Comment by ahhurlbert** [comment]
Numbers are lowest in those first figures which are 1x1 spatial grain. The larger grains farther down show decent numbers. Probably shouldn't bother doing any analysis at 1x1, although still might be worth including in the scale comparison.

**Comment by ethanwhite** [comment]
I'd looked further down and it seemed like it was consistently <10 species total. Am I misreading something or having unreasonable expectations for simulations? :smile:

**Comment by ahhurlbert** [comment]
You're right. I was thinking of the converge32_d-9_ind_run_summary.pdf file, which shows that richness is indeed higher at the larger spatial grains.

So @jescoyle can you explain the discrepancy?

**Comment by jescoyle** [comment]
Not sure what was going on with those plots. I fixed them to make the comparison across scale more explicit. Richness increases with scale as expected and basically saturates in 16x16  grid. It goes:

1x1 : 5
2x2 : 9
4x4: 17
8x8: 29
16x16: 38
