### ISSUE TITLE
Generating realistic SAD

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#14]
As we should have expected, giving species unequal fixed birth rates does not result in a realistic SAD. Instead, it appears that the species with the highest birth rates in each habitat type competitively exclude all other species in the metacommunity (eventually). Although this doesn't happen over the timeframe that we are looking at, it is not ideal behavior for the processes we are interested in evaluating.

So instead I think we should give all species a fixed birth (of 2) in their preferred habitat and generate unequal abundances artificially by starting the simulation with species sampled unequally according to the desired SAD. Not sure if this distribution will maintain itself through time, though... I'm checking with a simulation for 1000 steps.

Any other ideas?

**Comment by ethanwhite** [comment]
This sounds right to me and in line with how I think of neutral models 
working.

**Comment by ahhurlbert** [comment]
Sounds good. I suppose that the abundances will drift over time, but the overall distribution shouldn't differ too much?
