### ISSUE TITLE
Generalists

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#2]
The make_species() function can create species that are specialists in one habitat type (birth rate = 0 on non-preferred habitat) or generalists (birth rate > 0 and different in both habitat types).
1. Do we want to include generalists in the simulations?
2. Should there be a trade-off where generalists have either lower birth / higher mortality / lower recruitment than specialists?
3.  Should dispersal rates of specialists and generalists be different?

**Comment by ahhurlbert** [comment]
1-3. I'd say no generalists, at least as a starting point.
