### ISSUE TITLE
Species Vital Rates

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#3]
Below is a list of the way species vital rates are determined at the start of the simulation in the function make_species().

**Birth Rates** - number of offspring produced by an individual per time step.
Rates drawn from specified distribution (options: same, uniform, power-law, logseries, lognormal, poisson) parametrized by a given maximum rate or distribution-specific parameters.
1. Which distribution should we use?

**Death Rates** - probability that an individual will die per time step.
Rates are fixed at three possible values (for the preferred, non-preferred habitats, and for generalists).
1. Should death rates be age-specific?
2. Should death rates differ between preferred and non-preferred habitat types?

**Recruitment Rates** - probability that a propagule arriving in an open space will establish.
 Rates are fixed at three possible values (for the preferred, non-preferred habitats, and for generalists).
1. Should recruitment rates differ between preferred and non-preferred habitat types?

**Dispersal Rates** - Expected distance that a propagule will travel. 
Rates are drawn from a gamma distribution with given mean and variance. Actual distance traveled is determined stochastically assuming a gaussian dispersal kernel whose mean is the species dispersal rate.
1. Should all species have the same dispersal rate?
2. If not, how much variance in dispersal rates should there be? 
3. What range of dispersal rates should we simulate over?

**Comment by ahhurlbert** [comment]
Does it matter whether we build in the habitat-dependent vital rates into birth vs death rates vs both? If we're not getting into age-specific rates (Death Rates #1: no), etc then I don't really think it should.

_Recruitment Rates_: no, I would say probability should not differ between preferred and non-preferred.

_Dispersal Rates_:
1. Yes
2. Not sure of the parameters, but I'd say having ~1% chance of dispersing across 1/2 of the entire landscape would be in the ballpark.
3. I'd say let's have one simulation set with unlimited dispersal, and one with adjacent cell only dispersal, in addition to the intermediate gamma distribution.
