### ISSUE TITLE
Initializing a Landscape

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#4]
The populate_landscape() function adds a given set of species to a given landscape. The function allows for many different ways to do this- we need to decide which one to use. Adding species to a landscape occurs in three steps:

**Determine carrying capacity of each cell**
1. Should all cells have the same carrying capacity? What value?
2. Should cells have different, randomly determined capacities?

**Determine how many species should be allocated to each cell**
There are three options- A) all cells have the same proportion of their capacity filled, B) the entire landscape has a fixed proportion of its total carrying capacity filled, C) designated cells receive a fixed number of individuals or proportion of their carrying capacity.
1. Should we initialize the simulation on an empty grid, or use option A, B, or C?
2. What proportion of the carrying capacity should be filled initially?

**Choose species that establish in each cell**
Species are drawn from a global species abundance distribution.
1. Should all species have equal probability of being chosen?
2. If not, which distribution should be used? (See make_sad() function).

**Comment by ahhurlbert** [comment]
**Determine carrying capacity**
1. Yes. I don't know. 
2. No.

**Determine how many species should be allocated to each cell**
I would say the landscape gets initialized with all cells at capacity...

**Choose species that establish in each cell**
...with a random draw from the global SAD
