### ISSUE TITLE
Dispersal

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#6]
The disperse() function takes a pool of propagules from an origin cell and stochastically determines the cells they move to based on species-specific dispersal rates (_d_: mean dispersal distance). The distance that an individual propagule moves is drawn from a half-normal distribution whose mean is _d_ and the direction it moves is drawn uniformly from [0, 360]. The cell that the propagule lands in is determined by adding this dispersal vector to a randomly chosen location within the cell of origin.
1. Is a gaussian dispersal kernel sufficient? Should I implement a different distribution? Population-based dispersal kernels often have fatter tails, but I'm not sure whether this is needed for individual movement.

**Comment by ahhurlbert** [comment]
I don't think the details of the dispersal kernel matter much for our purposes. 

As I mentioned in another comment, however, it would be good to include the two extreme possibilities-- unlimited dispersal, and dispersal constrained only to adjacent cells--to bracket some intermediate level.

**Comment by jescoyle** [comment]
I just added two more options in the get_dispersal_vec() function that allow adjacent cell dispersal (with 1+ steps) and uniform dispersal (which allows for unlimited dispersal if provided with a max dispersal distance = landscape size). Adjacent cell dispersal requires an additional parameter giving the probability that a propagule will move from it's cell of origin. What should this probability be? Maybe 0.5? Using 0.2 would mean that a propagule has equal probability of remaining in the same cell or moving in one of the cardinal directions.
