### ISSUE TITLE
Order of Operations

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#7]
In one timestep of the simulation operations occur in the following order:

1) Birth - new propagules born.
2) Dispersal - propagules disperse
3) Establishment/recruitment - empty spaces colonized by propagules and immigrants.
4) Death - established individuals die.

Hence, individuals may establish and die in the same timestep. 

Should this order be changed?

**Comment by ahhurlbert** [comment]
I think this is reasonable. 

Just checking: given the current approach for modeling birth and death rates, it would not make sense to allow for dispersal of colonists that temporarily exceeds a cell's carrying capacity (only to be pruned back down during the Death step), right?

Is density-dependence getting incorporated into these rates? How?

**Comment by jescoyle** [comment]
At the moment, all propagules disperse (possibly staying within the same cell) and any excess propagules that do not colonize an empty space in the cell that they land in during a given timestep die. (This could be changed to allow propagules to have a lifespan beyond one timestep. )

Density-dependence is not incorporated in into birth or death rates, but is handled implicitly. That is, we assume that if an individual has 'captured' a space in the community (which has fixed K) then it has also captured enough resources to produce _b_ offspring each time step (a rate which is species-specific).

**Comment by ahhurlbert** [comment]
New order of operations per our phone call:

1) Death
2) Birth
3) Dispersal (of both propagules AND established individuals, which is new)
4) Establishment
