### ISSUE TITLE
Multiple runs on the same set of parameters

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#8]
The function run_sim_N starts and runs a given number of simulations using the same set of parameter values. However, each time it runs it generates a new landscape, a new set of species, and a new global species abundance distribution.

Should any of these initial objects remain the same across multiple runs?

**Comment by ahhurlbert** [comment]
Not entirely sure...

First instinct is that this is fine, and that we don't care about replicating any of these things specifically.
